### PR TITLE
handling client

### PR DESCRIPTION
**Pull request by NeoDitjoe**

### CODE REVIEW

**Comment by Tirelo-Mputle** [comment]
image
It looks like we are still creating different clients in the different files. Can we maybe create it once in the index file and then export  it?

**Review by Tirelo-Mputle — CHANGES_REQUESTED** [review]
image
Sorry, I now see that you initialized it here. Can we then export this client for the other files to use?

**Comment by NeoDitjoe** [comment]
That is now what is happening Tirelo. 
It is one client being called to other files

on the first picture you sent its importing from the second picture

Please re check, 
and/or ask Elzabe and Renzo to confirm if the code is correct, in case I understand your question.

**Review by Paskay18 — APPROVED** [review]
Reviewed

**Pull request closed without merging**
