### PR TITLE
Created tags container to display all tags

### PR DESCRIPTION
**Pull request by Tirelo-Mputle**
Tag component displays the name of the tag

### CODE REVIEW

**Review by Renzo-codespace — COMMENTED** [review]
Just waiting for the base project to be added to the main branch.

**Review by ElzabeEls — DISMISSED** [review]
Adding Tag component

**Review by Renzo-codespace — APPROVED** [review]
Looks great!
Keep going!

**Comment by ElzabeEls** [comment]
image
Did you check the Vercel feedback?

**Pull request merged**
