### PR TITLE
Description load failure#12

### PR DESCRIPTION
**Pull request by NeoDitjoe**

### CODE REVIEW

**Review by Tirelo-Mputle — APPROVED** [review]
Approved

**Review by ElzabeEls — APPROVED** [review]
looks good

**Comment by ElzabeEls** [comment]
@NeoDitjoe Please choose which one of the two options to keep to resolve the conflict

**Review by ElzabeEls — APPROVED** [review]
Small changes and error handing. Approved

**Review by Tirelo-Mputle — APPROVED** [review]
Approved.

**Pull request merged**
