### PR TITLE
Authentication

### PR DESCRIPTION
**Pull request by NeoDitjoe**
If you were using /database/updateData it is now @/database/client

### CODE REVIEW

**Review by Paskay18 — DISMISSED** [review]
Reviewed

**Review by Paskay18 — APPROVED** [review]
Reviewed

**Review by GirlKat17 — APPROVED** [review]
spell check and redirect. please change from [get an account] to [create an account ]

**Comment by NeoDitjoe** [comment]
Thank you Renzo😅

**Pull request merged**
