### PR TITLE
Completed issue 23 and 24

### PR DESCRIPTION
**Pull request by Paskay18**

### CODE REVIEW

**Comment by ElzabeEls** [comment]
Please run npm run build to check for any build errors and make sure all the Vercel checks pass

**Review by NeoDitjoe — APPROVED** [review]
All good

**Review by Renzo-codespace — APPROVED** [review]
We'll have to handle the connection string more securely in the future.

**Comment by ElzabeEls** [comment]
Conflicts resolved

**Review by NeoDitjoe — CHANGES_REQUESTED** [review]
1. fetch data from the .env file.
2. Commit your slug index file and your all recipes only.
3. In the main index don't mofify what is already there, Let Ona fix her own mistake. Only add what you need in the main index, in this case it is your button.
4. Don't commit the change, you made in the tags file, unless you spoke with its creatore

**Pull request closed without merging**
