### PR TITLE
Added homewithbackground.js

### PR DESCRIPTION
**Pull request by OnalennaRammapatsi**
Created a component for our home page and added the logo.

### CODE REVIEW

**Review by Otsile076 — APPROVED** [review]
approve

**Review by Paskay18 — DISMISSED** [review]
Reviewed

**Review by Paskay18 — APPROVED** [review]
Reviewed

**Review by Kelello-7206 — APPROVED** [review]

**Review by Otsile076 — APPROVED** [review]

**Comment by OnalennaRammapatsi** [comment]
Created a home page, added  the background image and the logo

**Pull request merged**
