### PR TITLE
Style

### PR DESCRIPTION
**Pull request by NeoDitjoe**

### CODE REVIEW

**Comment by Paskay18** [comment]
Please check the conflicting files

**Review by GirlKat17 — DISMISSED** [review]

**Review by OnalennaRammapatsi — DISMISSED** [review]
Looks okay.

**Review by OnalennaRammapatsi — DISMISSED** [review]
Approved changes.

**Review by GirlKat17 — APPROVED** [review]

**Review by OnalennaRammapatsi — APPROVED** [review]
Approved changes.

**Pull request merged**
