### PR TITLE
installed Next Js

### PR DESCRIPTION
**Pull request by NeoDitjoe**

### CODE REVIEW

**Review by Renzo-codespace — APPROVED** [review]
This pull requests includes changes beyond the description.
Please keep the changes and description of future pull requests in sync.
Well done, though! Keep making progress.

**Comment by Renzo-codespace** [comment]
@NeoDitjoe Please request another review, and let's keep this going!
Keep it up!

**Comment by Renzo-codespace** [comment]
image

@NeoDitjoe 
So Assignees are the people who will be working on the code for this pull request.
Reviewers are, well, reviewers.
Maybe add another reviewer, they'll be notified.

**Review by GirlKat17 — COMMENTED** [review]
approving the installation of next

**Comment by ElzabeEls** [comment]
NextJs Installation and MUI installation could have been different commits

**Review by ElzabeEls — APPROVED** [review]

**Pull request merged**
