### PR TITLE
Otsile Issue 13

### PR DESCRIPTION
**Pull request by Otsile076**
Recipe descriptions are showing

### CODE REVIEW

**Review by OnalennaRammapatsi — APPROVED** [review]
Descriptions for the recipes are displayed. All good.

**Review by ElzabeEls — CHANGES_REQUESTED** [review]
Are you sure you want to use router.push(`${100}`) as the page route?

**Comment by Otsile076** [comment]
No, we are going to change the code over the weekend because we discovered the logic we used doesn't work the way we want to according to our issues.

**Comment by ElzabeEls** [comment]
Conflicts resolved

**Comment by NeoDitjoe** [comment]
@ElzabeEls the use of "router.push(${100})" 
will be explained with a demostration during our meeting tomorrow

@Otsile076, you modifies 12 files to add a description

**Review by NeoDitjoe — CHANGES_REQUESTED** [review]
@Otsile076, you modified 12 files to add a description. 😩

commit only the file which you are displaying the description. I doubt it is 12 files

**Review by GirlKat17 — APPROVED** [review]
changed

**Review by OnalennaRammapatsi — APPROVED** [review]
Approved.

**Review by NeoDitjoe — APPROVED** [review]
see the changes

**Review by ElzabeEls — APPROVED** [review]
Approved

**Review by OnalennaRammapatsi — APPROVED** [review]

**Pull request merged**
