### PR TITLE
Style add to favourites button

### PR DESCRIPTION
**Pull request by Tirelo-Mputle**
Styled favourites button

### CODE REVIEW

**Review by Otsile076 — DISMISSED** [review]
Approved

**Review by Paskay18 — APPROVED** [review]
Reviewed

**Comment by Paskay18** [comment]
There are conflicts

**Review by NeoDitjoe — APPROVED** [review]

**Review by GirlKat17 — APPROVED** [review]
Approved

**Review by Otsile076 — APPROVED** [review]
Approved

**Review by Kelello-7206 — APPROVED** [review]
Approve

**Pull request merged**
