### PR TITLE
Single recipe style

### PR DESCRIPTION
**Pull request by Kelello-7206**

### CODE REVIEW

**Review by Otsile076 — APPROVED** [review]
Approved

**Review by GirlKat17 — APPROVED** [review]
approved

**Review by GirlKat17 — APPROVED** [review]
fix mobile view

**Review by Otsile076 — APPROVED** [review]
Approved

**Review by Tirelo-Mputle — APPROVED** [review]
Styled the single recipe page and changed the layout. Approved.

**Pull request merged**
