### PR TITLE
177 add favourite button to individual recipe page

### PR DESCRIPTION
**Pull request by Tirelo-Mputle**
Added "Add to favourites" button in single recipe page.

### CODE REVIEW

**Review by ElzabeEls — CHANGES_REQUESTED** [review]
image
Does this happen on your side as well?

**Comment by Tirelo-Mputle** [comment]
No, mine runs correctly. Try the Vercel preview provided in this pull request.

**Comment by Tirelo-Mputle** [comment]
This error seems like you might have an issue fetching the recipes. "documents" are the recipes fetched from the database.
image

**Comment by ElzabeEls** [comment]
> This error seems like you might have an issue fetching the recipes. "documents" are the recipes fetched from the database. image

Great feedback! Thank you! 💪🏼

**Review by ElzabeEls — APPROVED** [review]
I see you are adding context. We will have to keep an eye on it.

**Review by Otsile076 — APPROVED** [review]
approved

**Pull request merged**
